import type { OnboardingRecord, OnboardingDocument } from '@/types/database';

export const INITIAL_DEMO_ONBOARDINGS: OnboardingRecord[] = [
  {
    id: 'rec-001-prestige',
    brand_name: 'Prestige Estates',
    company_name: 'Prestige Group Projects Ltd',
    whatsapp_number: '+91 98450 12345',
    contact_person: 'Rahul Narang',
    contact_email: 'rahul.narang@prestige.com',
    contact_number: '+91 98450 12345',
    username: 'meta_prestige_bot',
    credential_encrypted: 'Immense#MetaSecret99',
    platform: 'Meta Cloud API (WABA)',
    login_url: 'https://business.facebook.com/wa/manage',
    status: 'live',
    assigned_to: 'demo-employee-003',
    onboarding_date: '2026-06-12',
    notes: 'Approved for 500k monthly interactive utility & marketing notifications.',
    created_by: 'demo-super-admin-001',
    created_at: '2026-06-12T10:00:00Z',
    updated_at: '2026-08-20T14:30:00Z',
  },
  {
    id: 'rec-002-tata',
    brand_name: 'Tata Motors EV',
    company_name: 'Tata Passenger Electric Mobility Ltd',
    whatsapp_number: '+91 99000 88776',
    contact_person: 'Ananya Deshmukh',
    contact_email: 'ananya.d@tatamotors.com',
    contact_number: '+91 99000 88776',
    username: 'tata_ev_support',
    credential_encrypted: 'TataMetaAuth2026!',
    platform: 'Meta Cloud API',
    login_url: 'https://business.facebook.com',
    status: 'in_progress',
    assigned_to: 'demo-employee-003',
    onboarding_date: '2026-08-01',
    notes: 'Green tick verified; waiting for message template approval for Nexon EV service alerts.',
    created_by: 'demo-manager-002',
    created_at: '2026-08-01T11:00:00Z',
    updated_at: '2026-08-22T09:15:00Z',
  },
  {
    id: 'rec-003-apollo',
    brand_name: 'Apollo Diagnostics',
    company_name: 'Apollo Health & Lifestyle Ltd',
    whatsapp_number: '+91 91234 56789',
    contact_person: 'Dr. S. Kulkarni',
    contact_email: 'dr.kulkarni@apollohealth.com',
    contact_number: '+91 91234 56789',
    username: 'apollo_dx_api',
    credential_encrypted: 'Apollo#Secure2026',
    platform: 'Gupshup Enterprise Gateway',
    login_url: 'https://enterprise.gupshup.io',
    status: 'pending',
    assigned_to: 'demo-manager-002',
    onboarding_date: '2026-08-20',
    notes: 'Medical lab report dispatch bot setup in progress.',
    created_by: 'demo-super-admin-001',
    created_at: '2026-08-20T16:00:00Z',
    updated_at: '2026-08-20T16:00:00Z',
  },
  {
    id: 'rec-004-himalaya',
    brand_name: 'Himalaya Wellness',
    company_name: 'Himalaya Global Holdings Ltd',
    whatsapp_number: '+91 98860 54321',
    contact_person: 'Gaurav Sen',
    contact_email: 'gaurav.sen@himalaya.com',
    contact_number: '+91 98860 54321',
    username: 'himalaya_store_bot',
    credential_encrypted: 'Himalaya@2026Secret',
    platform: 'Meta Cloud API',
    login_url: 'https://business.facebook.com',
    status: 'completed',
    assigned_to: 'demo-employee-003',
    onboarding_date: '2026-05-18',
    notes: 'E-commerce WhatsApp store live with UPI Pay on WhatsApp enabled.',
    created_by: 'demo-manager-002',
    created_at: '2026-05-18T12:00:00Z',
    updated_at: '2026-07-10T11:00:00Z',
  },
];

export const INITIAL_DEMO_DOCUMENTS: any[] = [
  {
    id: 'doc-001-prestige-gst',
    onboarding_id: 'rec-001-prestige',
    file_name: 'Prestige_GST_Registration_Certificate_2026.pdf',
    original_name: 'Prestige_GST_Registration_Certificate_2026.pdf',
    category: 'gst_certificate',
    storage_path: 'rec-001-prestige/gst_certificate/Prestige_GST.pdf',
    mime_type: 'application/pdf',
    file_size: 245000,
    uploaded_by: 'demo-super-admin-001',
    created_at: '2026-06-12T10:30:00Z',
    onboarding: {
      id: 'rec-001-prestige',
      brand_name: 'Prestige Estates',
      company_name: 'Prestige Group Projects Ltd',
      whatsapp_number: '+91 98450 12345',
      status: 'live',
    },
    uploader_profile: {
      id: 'demo-super-admin-001',
      full_name: 'Vikram Mehta',
      corporate_email: 'admin@immenseair.com',
    },
  },
  {
    id: 'doc-002-prestige-pan',
    onboarding_id: 'rec-001-prestige',
    file_name: 'Prestige_Corporate_PAN_Card.png',
    original_name: 'Prestige_Corporate_PAN_Card.png',
    category: 'pan',
    storage_path: 'rec-001-prestige/pan/Prestige_PAN.png',
    mime_type: 'image/png',
    file_size: 512000,
    uploaded_by: 'demo-super-admin-001',
    created_at: '2026-06-12T10:35:00Z',
    onboarding: {
      id: 'rec-001-prestige',
      brand_name: 'Prestige Estates',
      company_name: 'Prestige Group Projects Ltd',
      whatsapp_number: '+91 98450 12345',
      status: 'live',
    },
    uploader_profile: {
      id: 'demo-super-admin-001',
      full_name: 'Vikram Mehta',
      corporate_email: 'admin@immenseair.com',
    },
  },
  {
    id: 'doc-003-prestige-meta',
    onboarding_id: 'rec-001-prestige',
    file_name: 'Prestige_Meta_Business_Approval_Official.pdf',
    original_name: 'Prestige_Meta_Business_Approval_Official.pdf',
    category: 'whatsapp_approval',
    storage_path: 'rec-001-prestige/whatsapp_approval/Meta_Approval.pdf',
    mime_type: 'application/pdf',
    file_size: 380000,
    uploaded_by: 'demo-manager-002',
    created_at: '2026-06-15T14:00:00Z',
    onboarding: {
      id: 'rec-001-prestige',
      brand_name: 'Prestige Estates',
      company_name: 'Prestige Group Projects Ltd',
      whatsapp_number: '+91 98450 12345',
      status: 'live',
    },
    uploader_profile: {
      id: 'demo-manager-002',
      full_name: 'Priya Sharma',
      corporate_email: 'manager@immenseair.com',
    },
  },
  {
    id: 'doc-004-tata-gst',
    onboarding_id: 'rec-002-tata',
    file_name: 'Tata_Motors_GST_Certificate_Form_REG06.pdf',
    original_name: 'Tata_Motors_GST_Certificate_Form_REG06.pdf',
    category: 'gst_certificate',
    storage_path: 'rec-002-tata/gst_certificate/Tata_GST.pdf',
    mime_type: 'application/pdf',
    file_size: 420000,
    uploaded_by: 'demo-manager-002',
    created_at: '2026-08-01T11:20:00Z',
    onboarding: {
      id: 'rec-002-tata',
      brand_name: 'Tata Motors EV',
      company_name: 'Tata Passenger Electric Mobility Ltd',
      whatsapp_number: '+91 99000 88776',
      status: 'in_progress',
    },
    uploader_profile: {
      id: 'demo-manager-002',
      full_name: 'Priya Sharma',
      corporate_email: 'manager@immenseair.com',
    },
  },
];
